### ISSUE TITLE
Use free license underwater sound (its better, too)

### ISSUE THREAD

**Issue by MisterE123** [ThePeasantJoe/Better-Water-Physics-Minetest#2]
https://freesound.org/people/Kinoton/sounds/393819/

This sound for underwater is CC0, so you could remove the noncommercial underwater sound and get more visibility on CDB.

Besides, I think this underwater sound is better

**Comment by ThePeasantJoe** [comment]
hey, thanks alot man. I'll add it. Really appreciate it!

**Comment by ThePeasantJoe** [comment]
so, would you advise me doing it for a splash or just underwater ambience?

**Comment by MisterE123** [comment]
I would suggest using it to replace the CC-by-NC sound. Other than that,
use it whatever way you like.

**Comment by ThePeasantJoe** [comment]
alright, thanks for all the help!

**Comment by ThePeasantJoe** [comment]
got it all updated, thanks man!
